language: go
sudo: required
go:
  - 1.6.3
  - 1.7.1
  - tip
os:
  - linux
  - osx
  
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
